### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ausername-1**
## Summary
This fixes a typo to import a couple of files.

Issue #13

### CODE REVIEW

**Comment by carsonwltz** [comment]
Does this actually fix anything?

**Comment by ausername-1** [comment]
Read the title.

**Comment by carsonwltz** [comment]
So a capitalization change is a typo?

**Comment by ausername-1** [comment]
Try compiling the code without the Capitalization change.

**Comment by kevinjosethomas** [comment]
1. Please read our contributing guidelines, you need to first create an issue and request to be assigned to it before you create a pull request.
2. Change the filename instead of the import statement, I changed this earlier but there seems to be an issue in Windows with case insensitive version control.

I'm closing this pull request and I'll assign you to the issue so you can create a new one with a different filename if you are interested

**Pull request closed without merging**
